#! /usr/bin/env python3

from pathlib import Path
from shutil import which
from subprocess import run
from sys import platform

FILES = [
    Path("~/.config/ghostty/config.ghostty").expanduser(),
    Path("~/.config/tmux/tmux.conf").expanduser(),
    Path("~/.zshrc").expanduser(),
]
TOOLS = [
    ["bat", "batcat"],
    ["chafa"],
    ["fd", "fdfind"],
    ["fzf"],
    ["gcc", "cc"],
    ["gh"],
    ["git"],
    ["magick", "convert"],
    ["make", "gmake"],
    ["mise", "rtx"],
    ["nvim"],
    ["rg"],
    ["tms"],
    ["tmux"],
    ["tpm"],
    ["tree-sitter"],
    ["zoxide"],
    ["xcode", "xcode-select", "xcodebuild"],
    ["zsh"],
]
LANGUAGES = [
    "go",
    "node",
    "python3",
]

TPM_PATH = Path("~/.tmux/plugins/tpm").expanduser()

NO_EMOJI = "❌"
YES_EMOJI = "✅"


def mise_which(tool: str) -> str:
    return run(["mise", "which", tool], capture_output=True, text=True).stdout.strip()


def xcode_select() -> str:
    return run(["xcode-select", "-p"], capture_output=True, text=True).stdout.strip()


def print_status(tool: str, path: str | None, is_found: bool):
    emoji = YES_EMOJI if is_found else NO_EMOJI
    path = None if path is not None and len(path) == 0 else path
    print(f"{emoji} {tool:<15}: {path}")


def main():
    print("Dotfiles:")
    for file in FILES:
        print_status(file.name, str(file), file.is_file())

    print("\nTools:")
    for tool_names in TOOLS:
        path = None
        for tool in tool_names:
            if bool(path):
                break

            if tool == "tpm" and TPM_PATH.is_dir() and any(TPM_PATH.iterdir()):
                path = str(TPM_PATH)
            elif "xcode" in tool:
                if not platform.startswith("darwin"):
                    continue
                path = xcode_select()
            else:
                path = which(tool)
                path = "" if path is None else path

        if not path is None:
            print_status(tool_names[0], path, bool(path))

    print("\nLanguages:")
    is_mise_installed = bool(which("mise"))
    for language in LANGUAGES:
        path = None if not is_mise_installed else mise_which(language)
        print_status(language, path, bool(path))


if __name__ == "__main__":
    main()
